### ISSUE TITLE
Rule out incorrect flags

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/colorls#10]
Redirecting from issue #4 

```
$ lc -a                                                                 123ms  Saturday 01 July 2017 07:53:57 PM IST
colorls/colorls.rb:10:in `open': No such file or directory @ dir_initialize - -a (Errno::ENOENT)
	from colorls/colorls.rb:10:in `entries'
	from colorls/colorls.rb:10:in `initialize'
	from colorls/colorls.rb:121:in `new'
	from colorls/colorls.rb:121:in `block in <main>'
	from colorls/colorls.rb:121:in `each'
	from colorls/colorls.rb:121:in `<main>'
```

**Comment by athityakumar** [comment]
Fixed with commit 8d55ba207be36e6f84b1762eeaf1313c7d7e6959
