### ISSUE TITLE
"undefined method `to_h' in `load_from_yaml'"

### ISSUE THREAD

**Issue by MojoBandit** [athityakumar/colorls#162]
### Description

Install went fine but when I try to execute `colorls` I get this:

```
/Library/Ruby/Gems/2.0.0/gems/colorls-1.0.9/lib/colorls/load_from_yaml.rb:16:in `load_from_yaml': undefined method `to_h' for #<Array:0x007fcd71945d90> (NoMethodError)
        from /Library/Ruby/Gems/2.0.0/gems/colorls-1.0.9/lib/colorls/flags.rb:130:in `set_color_opts'
        from /Library/Ruby/Gems/2.0.0/gems/colorls-1.0.9/lib/colorls/flags.rb:125:in `parse_options'
        from /Library/Ruby/Gems/2.0.0/gems/colorls-1.0.9/lib/colorls/flags.rb:21:in `initialize'
        from /Library/Ruby/Gems/2.0.0/gems/colorls-1.0.9/exe/colorls:4:in `new'
        from /Library/Ruby/Gems/2.0.0/gems/colorls-1.0.9/exe/colorls:4:in `<top (required)>'
        from /usr/local/bin/colorls:23:in `load'
        from /usr/local/bin/colorls:23:in `<main>'
```

- Type of issue :
  - [x] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

### Context

MacOS X Sierra (10.12.6)

ruby 2.4.2p198

*** LOCAL GEMS ***
bigdecimal (default: 1.3.0)
did_you_mean (1.1.0)
io-console (default: 0.4.6)
json (default: 2.0.4)
minitest (5.10.1)
net-telnet (0.1.1)
openssl (default: 2.0.5)
power_assert (0.4.1)
psych (default: 2.2.2)
rake (12.0.0)
rdoc (default: 5.0.0)
test-unit (3.2.3)
xmlrpc (0.2.1)

Thanks.

**Comment by MojoBandit** [comment]
Ok so I reinstalled everything and it seems to work fine now.

Sorry about that.
