### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by octoxan** [athityakumar/colorls#176]
Trying to install colorls, and am getting the following error...

```
Building native extensions. This could take a while...
ERROR:  Error installing colorls:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/clocale-0.0.3/ext/clocale
/usr/bin/ruby2.3 -r ./siteconf20180115-9559-ml4gl.rb extconf.rb
checking for locale.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.3.0/mkmf.rb:587:in `try_cpp'
	from /usr/lib/ruby/2.3.0/mkmf.rb:1091:in `block in have_header'
	from /usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
	from extconf.rb:9:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/clocale-0.0.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/clocale-0.0.3 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/clocale-0.0.3/gem_make.out
```

Here is what's in said log...
```
"gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.3.0 -I/usr/include/ruby-2.3.0/ruby/backward -I/usr/include/ruby-2.3.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -fstack-protector-strong -Wformat -Werror=f$
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by athityakumar** [comment]
@avdv - Are there any extensions to install before installing clocale gem?

**Comment by avdv** [comment]
No, `clocale` does not need any extension. But building it requires a working compiler, seems that the simple C program failed to compile:

> You have to install development tools first.

@octoxan What OS / distribution are you using? Try to install gcc...

**Comment by octoxan** [comment]
@avdv Running a fresh install of Ubuntu 16.04 server.

After doing `sudo apt-get install gcc`, my new error is...

```
Building native extensions. This could take a while...
ERROR:  Error installing colorls:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/clocale-0.0.3/ext/clocale
/usr/bin/ruby2.3 -r ./siteconf20180116-29031-v8ubre.rb extconf.rb
checking for locale.h... yes
checking for setlocale()... yes
checking for strcoll()... yes
checking for strxfrm()... yes
creating Makefile

current directory: /var/lib/gems/2.3.0/gems/clocale-0.0.3/ext/clocale
make "DESTDIR=" clean
sh: 1: make: not found

current directory: /var/lib/gems/2.3.0/gems/clocale-0.0.3/ext/clocale
make "DESTDIR="
sh: 1: make: not found

make failed, exit code 127

Gem files will remain installed in /var/lib/gems/2.3.0/gems/clocale-0.0.3 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/clocale-0.0.3/gem_make.out
```

**Comment by octoxan** [comment]
Ah, now after installing make, it works!
