### ISSUE TITLE
--tree=1  needless argument ubuntu 18.04

### ISSUE THREAD

**Issue by anoopd** [athityakumar/colorls#254]
In Ubuntu 18.04 the `--tree=` option is giving the error 

    Traceback (most recent call last):
	5: from /usr/local/bin/colorls:23:in `<main>'
	4: from /usr/local/bin/colorls:23:in `load'
	3: from /var/lib/gems/2.5.0/gems/colorls-1.1.1/exe/colorls:5:in `<top (required)>'
	2: from /var/lib/gems/2.5.0/gems/colorls-1.1.1/exe/colorls:5:in `new'
	1: from /var/lib/gems/2.5.0/gems/colorls-1.1.1/lib/colorls/flags.rb:24:in `initialize'
    /var/lib/gems/2.5.0/gems/colorls-1.1.1/lib/colorls/flags.rb:161:in `parse_options': needless argument: -- 
   tree=2 (OptionParser::NeedlessArgument)

**Comment by avdv** [comment]
The depth argument of the `--tree` option was only introduced recently and has not been released yet. You have to install colors from source of you want to use it

**Comment by anoopd** [comment]
ok thank you
