### ISSUE TITLE
Broken after brew upgrade

### ISSUE THREAD

**Issue by mickaelperrin** [athityakumar/colorls#280]
Hi,

I did a `brew upgrade` on my mac and `colorls` is now broke :(

```
# colorls
Ignoring clocale-0.0.4 because its extensions are not built. Try: gem pristine clocale --version 0.0.4
Traceback (most recent call last):
	10: from /usr/local/bin/colorls:23:in `<main>'
	 9: from /usr/local/bin/colorls:23:in `load'
	 8: from /Users/mickaelperrin/.gem/gems/colorls-1.2.0/exe/colorls:4:in `<top (required)>'
	 7: from /usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/mickaelperrin/.gem/gems/colorls-1.2.0/lib/colorls.rb:9:in `<top (required)>'
	 4: from /usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Users/mickaelperrin/.gem/gems/clocale-0.0.4/lib/clocale.rb:15:in `<top (required)>'
	 1: from /usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': incompatible library version - /Users/mickaelperrin/.gem/gems/clocale-0.0.4/lib/clocale/clocale.bundle (LoadError)
```

I tried the following without success:

```
gem update colorls
gem pristine clocale --version 0.0.4
gem pristine clocale
gem uninstall colorls; gem install colorls
```

Any hints to resolve this issue ?

Thanks,

**Comment by mickaelperrin** [comment]
Resolve by reinstalling with `sudo`.

**Comment by Maf-H** [comment]
run the following command as admin >"sudo gem pristine clocale --version 0.0.4"
