### ISSUE TITLE
Installation failure on macOS Catalina

### ISSUE THREAD

**Issue by BaozCWJ** [athityakumar/colorls#318]
After updating MacOS Catalina and reinstall command line tools, I found a installation failure similar to #238 ,but the directory `/Library/Developer/CommandLineTools/Packages` doesn't exist.

```
Building native extensions. This could take a while...
ERROR:  Error installing colorls:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.6.0/gems/clocale-0.0.4/ext/clocale
/usr/local/opt/ruby/bin/ruby -I /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0 -r ./siteconf20191009-16584-1l4uiw9.rb extconf.rb
checking for locale.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/Cellar/ruby/2.6.5/bin/$(RUBY_BASE_NAME)
/usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/mkmf.rb:601:in `try_cpp'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/mkmf.rb:1109:in `block in have_header'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
	from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/mkmf.rb:1108:in `have_header'
	from extconf.rb:9:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-19/2.6.0/clocale-0.0.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.6.0/gems/clocale-0.0.4 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-19/2.6.0/clocale-0.0.4/gem_make.out 
```

### Description

Thanks for opening this issue. Add a brief description of what this issue is, and how to recreate it. Do tag the relevant issue(s) and PR(s) below. If required, add some screenshot(s) to showcase the issue.

- Relevant Issues : #238  #176 
- Relevant PRs : (none)
- Type of issue :
  - [x] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by rolzing** [comment]
![image](https://user-images.githubusercontent.com/12732319/66454336-31b6c400-ea2d-11e9-91da-42dc48d83fd8.png)

I have an issue on mac os catalina too, not sure if it's related.

**Comment by avdv** [comment]
> To see why this extension failed to compile, please check the mkmf.log which can be found here:
> 
>   /usr/local/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-19/2.6.0/clocale-0.0.4/mkmf.log

???

**Comment by avdv** [comment]
> I have an issue on mac os catalina too, not sure if it's related.

Not related. You do not (no longer?) have Ruby 2.3 installed. `ruby --version` ? You probably need to reinstall colorls.

**Comment by BaozCWJ** [comment]
> > To see why this extension failed to compile, please check the mkmf.log which can be found here:
> > /usr/local/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-19/2.6.0/clocale-0.0.4/mkmf.log
> 
> ???

```
"clang -o conftest -I/usr/local/Cellar/ruby/2.6.5/include/ruby-2.6.0/x86_64-darwin19 -I/usr/local/Cellar/ruby/2.6.5/include/ruby-2.6.0/ruby/backward -I/usr/local/Cellar/ruby/2.6.5/include/ruby-2.6.0 -I.  -I/usr/local/opt/libyaml/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens  -fno-common -pipe conftest.c  -L. -L/usr/local/Cellar/ruby/2.6.5/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib     -lruby.2.6   "
In file included from conftest.c:1:
In file included from /usr/local/Cellar/ruby/2.6.5/include/ruby-2.6.0/ruby.h:33:
In file included from /usr/local/Cellar/ruby/2.6.5/include/ruby-2.6.0/ruby/ruby.h:29:
/usr/local/Cellar/ruby/2.6.5/include/ruby-2.6.0/ruby/defines.h:123:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by avdv** [comment]
@BaozCWJ maybe this helps:
> You should install macOS SDK headers from /Library/Developer/CommandLineTools/Packages/

(from https://stackoverflow.com/questions/57746792/homebrews-llvm-fatal-error-stdio-h-file-not-found-on-macos)

**Comment by BaozCWJ** [comment]
> @BaozCWJ maybe this helps:
> 
> > You should install macOS SDK headers from /Library/Developer/CommandLineTools/Packages/
> 
> (from https://stackoverflow.com/questions/57746792/homebrews-llvm-fatal-error-stdio-h-file-not-found-on-macos)

But there's no such directory or pkg under /Library/Developer/CommandLineTools

**Comment by avdv** [comment]
@BaozCWJ try this:
https://github.com/frida/frida/issues/338#issuecomment-328462701

**Comment by avdv** [comment]
And see here: https://forums.developer.apple.com/thread/104296

**Comment by sukheja-varun** [comment]
It got fixed with steps mentioned here
https://stackoverflow.com/a/58310557/6715606

**Comment by BaozCWJ** [comment]
> It got fixed with steps mentioned here
> https://stackoverflow.com/a/58310557/6715606

It worked! Thx
