### ISSUE TITLE
Strange error propably related with ruby gem version

### ISSUE THREAD

**Issue by Privth** [athityakumar/colorls#333]
After type `ls` this output display:

```
Traceback (most recent call last):
	2: from /usr/bin/colorls:23:in `<main>'
	1: from /usr/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
/usr/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem colorls (>= 0.a) with executable colorls (Gem::GemNotFoundException)
```

**Comment by avdv** [comment]
You probably upgraded Ruby. In this case you have to re-install colorls since gems are installed per major.minor version and cannot be found when you switch it.

**Comment by ykonstant1** [comment]
The solution from another thread was to reinstall colorls with `gem install colorls'.

**Comment by Privth** [comment]
why when i did it with sudo it didnt work?

**Comment by avdv** [comment]
> why when i did it with sudo it didnt work?

@privth Need more info. What did you do? What did not work? What was the output?

Guessing: root uses a different Ruby version than your user.

**Comment by jj-dominguez** [comment]
I had the same issue, but only when using colorls in the integrated terminal in VSCode. Reinstalling worked as @ykonstant1 suggested, but then I ran into issues re-sourcing zsh. I got these errors:

`Ignoring executable-hooks-1.6.0 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.0
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Error loading RubyGems plugin "/Users/jordandominguez/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/executable-hooks-1.6.0/lib/rubygems_plugin.rb": cannot load such file -- executable-hooks/wrapper (LoadError)
Error loading RubyGems plugin "/Users/jordandominguez/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/gem-wrappers-1.4.0/lib/rubygems_plugin.rb": cannot load such file -- gem-wrappers (LoadError)` 

These were fixed by running the `gem pristine` commands that were suggested.

**Comment by avdv** [comment]
@jj-dominguez I think using colorls with RVM is not really practical, since you would need to install colorls to each and every Ruby version managed by RVM as otherwise it will fail when you switch to a different version (which happens automatically if you have a .rmvrc in your project).

To get RVM out of the way and always use the system Ruby for colorls I would create a `colorls` shell function:
```shell
function colorls() {
  ( rvm system && command colorls "$@" )
}
```
