### ISSUE TITLE
Errors when ($gem env) or ($colorls) in $HOME's subdirectory on MAC

### ISSUE THREAD

**Issue by jaredyam** [athityakumar/colorls#342]
When I worked at my $HOME directory, the colorls works well with all recommend commands. But when I turned into the $HOME's subdirectory(my work dir), the ERRORs happened. Listing my work directory is a normal thing right? I cannot see anybody has the same trouble with me, so the problem might due to my installation? Here is a snippet of the ERROR information:

```
`~/Desktop
➜ “ “colorls
Traceback (most recent call last):
	13: from /Users/joeyam/.rbenv/versions/2.6.5/bin/colorls:23:in `<main>'
	12: from /Users/joeyam/.rbenv/versions/2.6.5/bin/colorls:23:in `load'
	11: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/colorls-1.3.3/exe/colorls:4:in `<top (required)>'
	10: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 9: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 8: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/colorls-1.3.3/lib/colorls.rb:3:in `<top (required)>'
	 7: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 6: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 5: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
	 4: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 2: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/2.6.0/psych.rb:14:in `<top (required)>'
	 1: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- 2.6/psych.so (LoadError)
	24: from /Users/joeyam/.rbenv/versions/2.6.5/bin/colorls:23:in `<main>'
	23: from /Users/joeyam/.rbenv/versions/2.6.5/bin/colorls:23:in `load'
	22: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/colorls-1.3.3/exe/colorls:4:in `<top (required)>'
	21: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	20: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	19: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/colorls-1.3.3/lib/colorls.rb:3:in `<top (required)>'
	18: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	17: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	16: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
	15: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	14: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	13: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/2.6.0/psych.rb:14:in `<top (required)>'
	12: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	11: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:161:in `rescue in require'
	10: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:204:in `try_activate'
	 9: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:996:in `find_by_path'
	 8: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:996:in `find'
	 7: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:996:in `each'
	 6: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:997:in `block in find_by_path'
	 5: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:39:in `compatible?'
	 4: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:7:in `bundler_version'
	 3: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:22:in `bundler_version_with_reason'
	 2: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:73:in `lockfile_version'
	 1: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:85:in `lockfile_contents'
/Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:85:in `pwd': No such file or directory - getcwd (Errno::ENOENT)`
```

I'm new to the ruby and gem, at the very beginning of meeting this trouble I had searching these errors log in Google for hours. It seems that in my present installation the $gem has the same trouble. Below is my basic install environment:

I used rbenv for installing. gems environment is
```
$ gem env

- EXECUTABLE DIRECTORY:$HOME/.rbenv/versions/2.6.5/bin
```

**Comment by avdv** [comment]
Why are you messing with rbenv? Do you use it actually?

Run `rbenv version` in your $HOME directory and in the directory where you get the error. What is the output?

**Comment by GoogolRen** [comment]
> Why are you messing with rbenv? Do you use it actually?
> 
> Run `rbenv version` in your $HOME directory and in the directory where you get the error. What is the output?

I have ruby and gems installed with rbenv.
brew -> rbenv
rbenv -> ruby,(2.6.5)
gem -> colorls

rbenv version:
```
➜ “ “rbenv --version
rbenv 1.1.2
~ took 3s
➜ “ “
```
change to a subdir:
```
➜ “ “cd Downloads
~/Downloads
➜ “ “rbenv --version
rbenv 1.1.2
~/Downloads
➜ “ “
```

**Comment by avdv** [comment]
I have no idea what might be causing this... try re-installing maybe?!

**Comment by GoogolRen** [comment]
> I have no idea what might be causing this... try re-installing maybe?!

I had tried this many times as well as reinstalled rbenv and ruby. The issue still exists.

**But** I found a new clue that this error may only exist in my $HOME/Documents and Downloads directory and it's straightforward because the $gem cannot works(The same error logging).

**Comment by avdv** [comment]
Maybe it's because those directories are some kind of links? Or it is an issue with case-insensitive file system? Ie. why would `getcwd` fail with "No such file or directory"?

Maybe this could help: https://stackoverflow.com/questions/9243548/no-such-file-or-directory-getcwd-error-on-rubygems-on-mac-os-lion

**Comment by GoogolRen** [comment]
It does not work for me. I had tried the following answers before posting this issue, For now, it seems that not a big deal if I do not execute `$colorls` commands in such directories directly(Downloads and Documents on mac).

**Comment by avdv** [comment]
You could also try to remove rbenv. Just install Ruby and install colorls.

**Comment by jaredyam** [comment]
I had tried to install `colorls` from `$brew install ruby` (not `rbenv`). The same issue exists so I changed to use `rbenv`. To valid again, I reproduce this issue in my local environment.

```
$echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.zshrc
$which ruby
/usr/local/opt/ruby/bin/ruby
$gem env
EXECUTABLE DIRECTORY: /usr/local/lib/ruby/gems/2.6.0/bin
$gem install colorls
$cd Documents
$colorls --tree # for example
```
The same following output:
```
Traceback (most recent call last):
	13: from /Users/joeyam/.rbenv/versions/2.6.5/bin/colorls:23:in `<main>'
	12: from /Users/joeyam/.rbenv/versions/2.6.5/bin/colorls:23:in `load'
	11: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/colorls-1.3.3/exe/colorls:4:in `<top (required)>'
	10: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 9: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 8: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/colorls-1.3.3/lib/colorls.rb:3:in `<top (required)>'
	 7: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 6: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 5: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
	 4: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 2: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/2.6.0/psych.rb:14:in `<top (required)>'
	 1: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- 2.6/psych.so (LoadError)
	24: from /Users/joeyam/.rbenv/versions/2.6.5/bin/colorls:23:in `<main>'
	23: from /Users/joeyam/.rbenv/versions/2.6.5/bin/colorls:23:in `load'
	22: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/colorls-1.3.3/exe/colorls:4:in `<top (required)>'
	21: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	20: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	19: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/colorls-1.3.3/lib/colorls.rb:3:in `<top (required)>'
	18: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	17: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	16: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
	15: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	14: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	13: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/2.6.0/psych.rb:14:in `<top (required)>'
	12: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	11: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:161:in `rescue in require'
	10: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:204:in `try_activate'
	 9: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:996:in `find_by_path'
	 8: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:996:in `find'
	 7: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:996:in `each'
	 6: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:997:in `block in find_by_path'
	 5: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:39:in `compatible?'
	 4: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:7:in `bundler_version'
	 3: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:22:in `bundler_version_with_reason'
	 2: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:73:in `lockfile_version'
	 1: from /Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:85:in `lockfile_contents'
/Users/joeyam/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:85:in `pwd': No such file or directory - getcwd (Errno::ENOENT)
```

Since the solutions from you mentioned before(the stack.. link) suggests the lastest version of gems is better, I also tried to update the version of gems and executed the following procedure same with above code:
```
$sudo gem update --system
```

Unfortunately it still no help!!! Thanks for your advice till now, this issue is not confusing me anymore because I can get comfortable using colorls only if escape the "bug" for me.

**Comment by jaredyam** [comment]
Damnit! It's just a silly question about the accessibility permission of my shell app `iTerms`. Since I modified the permission entries, this issue has been fixed for me and everything works well! While I get comfortable with this plugin, the same issue (#341 ) also appears with me, hope you can fix this bug soon!👍🏻

**Comment by jaredyam** [comment]
Damnit! It's just a silly question about the accessibility permission of my shell app iTerms. Since I modified the permission entries, this issue has been fixed for me and everything works well! While I get comfortable with this plugin, the same issue (#341 ) also appears with me, hope you can fix this bug soon!👍🏻

**Comment by h-jia** [comment]
From my experience (just happened), you are in a directory which you just **deleted**!. 

cd back and you will be all good!
