### ISSUE TITLE
colorls --git-status crashes with traceback

### ISSUE THREAD

**Issue by xbjfk** [athityakumar/colorls#371]
Running colorls with --git-status, colorls crashes with the following traceback:
```
Traceback (most recent call last):
        19: from /usr/bin/colorls:9:in `<main>'
        18: from /usr/bin/colorls:9:in `load'
        17: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/exe/colorls:26:in `<top (required)>'
        16: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/flags.rb:43:in `process'
        15: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/flags.rb:43:in `each_with_index'
        14: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/flags.rb:43:in `each'
        13: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/flags.rb:48:in `block in process'
        12: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/core.rb:48:in `ls'
        11: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/layout.rb:14:in `each_line'
        10: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/layout.rb:14:in `each'
         9: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/layout.rb:14:in `block in each_line'
         8: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/core.rb:49:in `block in ls'
         7: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/core.rb:301:in `ls_line'
         6: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/core.rb:301:in `each_with_index'
         5: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/core.rb:301:in `each'
         4: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/core.rb:302:in `block in ls_line'
         3: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/core.rb:295:in `fetch_string'
         2: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/core.rb:235:in `git_info'
         1: from /usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/core.rb:255:in `git_dir_info'
/usr/lib64/ruby/gems/2.5.0/gems/colorls-1.4.1/lib/colorls/git.rb:14:in `block in status': uninitialized constant ColorLS::Git::Set (NameError)
```
- Type of issue: Bug in existing feature

Thanks in advance :)

**Comment by avdv** [comment]
Hi. Thanks for the report! I cannot really reproduce this, so let's hope #372 fixes it for good...

**Comment by xbjfk** [comment]
#372 fixed this. Will close when merged.
