### ISSUE TITLE
Incompatible character encoding error

### ISSUE THREAD

**Issue by avdv** [athityakumar/colorls#377]
[...]/colorls/core.rb:86:in `join': **incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)**

I am not fluent in ruby I am more in shell script I understand the probleme is probably the «é» character in `/home/luxcium/Téléchargements` 

**Output:**
```
/home/luxcium/Téléchargements
Traceback (most recent call last):
        12: from /home/luxcium/bin/colorls:23:in `<main>'
        11: from /home/luxcium/bin/colorls:23:in `load'
        10: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/exe/colorls:26:in `<top (required)>'
         9: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/flags.rb:43:in `process'
         8: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/flags.rb:43:in `each_with_index'
         7: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/flags.rb:43:in `each'
         6: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/flags.rb:48:in `block in process'
         5: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/flags.rb:48:in `new'
         4: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/core.rb:29:in `initialize'
         3: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/core.rb:86:in `init_contents'
         2: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/core.rb:86:in `map!'
         1: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/core.rb:86:in `block in init_contents'
/home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/core.rb:86:in `join': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
/home/luxcium/Téléchargements
 
```

**My shell function in ZSH:**

```
    function ld() {
        (
            local mypath="${@:-$(pwd)}"
            echo ''
            builtin cd "${mypath}"
            pw
            colorls -lA --sd -d "${mypath}"
            pw
            echo "${mypath}"
        )
    }
```

**My locale:**
```
locale      
LANG=fr_CA.UTF-8
LC_CTYPE="fr_CA.UTF-8"
LC_NUMERIC=fr_CA.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE=fr_CA.UTF-8
LC_MONETARY=fr_CA.UTF-8
LC_MESSAGES="fr_CA.UTF-8"
LC_PAPER="fr_CA.UTF-8"
LC_NAME="fr_CA.UTF-8"
LC_ADDRESS="fr_CA.UTF-8"
LC_TELEPHONE="fr_CA.UTF-8"
LC_MEASUREMENT=fr_CA.UTF-8
LC_IDENTIFICATION="fr_CA.UTF-8"
LC_ALL=
```

_Originally posted by @Luxcium in https://github.com/athityakumar/colorls/issues/242#issuecomment-667871739_

**Comment by Luxcium** [comment]
Ho ok I guess this is what "opening my own issue would have looked like" I don't have the problem anymore but I don't remember what I did so let me get more information about my issue...

**Comment by simonbcn** [comment]
Same problem.
```
$ locale
LANG=es_ES.UTF-8
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER="es_ES.UTF-8"
LC_NAME="es_ES.UTF-8"
LC_ADDRESS="es_ES.UTF-8"
LC_TELEPHONE="es_ES.UTF-8"
LC_MEASUREMENT="es_ES.UTF-8"
LC_IDENTIFICATION="es_ES.UTF-8"
LC_ALL=

$ ls Imágenes
Traceback (most recent call last):
12: from /usr/bin/colorls:23:in `<main>'
11: from /usr/bin/colorls:23:in `load'
10: from /usr/lib/ruby/gems/2.7.0/gems/colorls-1.4.2/exe/colorls:26:in `<top (required)>'
9: from /usr/lib/ruby/gems/2.7.0/gems/colorls-1.4.2/lib/colorls/flags.rb:43:in `process'
8: from /usr/lib/ruby/gems/2.7.0/gems/colorls-1.4.2/lib/colorls/flags.rb:43:in `each_with_index'
7: from /usr/lib/ruby/gems/2.7.0/gems/colorls-1.4.2/lib/colorls/flags.rb:43:in `each'
6: from /usr/lib/ruby/gems/2.7.0/gems/colorls-1.4.2/lib/colorls/flags.rb:48:in `block in process'
5: from /usr/lib/ruby/gems/2.7.0/gems/colorls-1.4.2/lib/colorls/flags.rb:48:in `new'
4: from /usr/lib/ruby/gems/2.7.0/gems/colorls-1.4.2/lib/colorls/core.rb:29:in `initialize'
3: from /usr/lib/ruby/gems/2.7.0/gems/colorls-1.4.2/lib/colorls/core.rb:86:in `init_contents'
2: from /usr/lib/ruby/gems/2.7.0/gems/colorls-1.4.2/lib/colorls/core.rb:86:in `map!'
1: from /usr/lib/ruby/gems/2.7.0/gems/colorls-1.4.2/lib/colorls/core.rb:86:in `block in init_contents'
/usr/lib/ruby/gems/2.7.0/gems/colorls-1.4.2/lib/colorls/core.rb:86:in `join': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
```

**Comment by avdv** [comment]
I already tried to reproduce this, but I could not. Is `Imágenes` a directory? What's the contents of it? 

Note that I am AFC until next weekend...

**Comment by simonbcn** [comment]
```
$ exa -T Imágenes 
Imágenes
├── 20190419_125354.jpg
├── 20190419_125435.jpg
├── Cámara
│  ├── DSC_4728.JPG
│  ├── DSC_4730.JPG
│  ├── DSC_4731.JPG
│  ├── DSC_4733.JPG
│  ├── DSC_4734.JPG
│  ├── DSC_4741.JPG
│  ├── DSC_4742.JPG
│  ├── DSC_4748.JPG
│  ├── DSC_4749.JPG
│  ├── DSC_4752.JPG
│  ├── DSC_4753.JPG
│  ├── DSC_4755.JPG
│  ├── DSC_4758.JPG
│  ├── DSC_4761.JPG
│  ├── DSC_4763.JPG
│  ├── DSC_4765.JPG
│  ├── DSC_4766.JPG
│  ├── DSC_4767.JPG
│  ├── DSC_4769.JPG
│  ├── DSC_4773.JPG
│  ├── DSC_4777.JPG
│  ├── DSC_4779.JPG
│  ├── DSC_4780.JPG
│  ├── DSC_4782.JPG
│  ├── DSC_4784.JPG
│  ├── DSC_4787.JPG
│  ├── DSC_4788.JPG
│  ├── DSC_4789.JPG
│  ├── DSC_4790.JPG
│  ├── DSC_4792.JPG
│  ├── DSC_4794.JPG
│  ├── DSC_4797.JPG
│  ├── DSC_4807.JPG
│  ├── DSC_4808.JPG
│  ├── DSC_4809.JPG
│  ├── DSC_4810.JPG
│  ├── DSC_4811.JPG
│  ├── DSC_4812.JPG
│  ├── DSC_4813.JPG
│  ├── DSC_4814.JPG
│  ├── DSC_4815.JPG
│  └── DSC_4816.JPG
├── IMG_20191225_124838.jpg
├── IMG_20191225_124843.jpg
├── IMG_20200101_135407.jpg
└── mifoto1.jpg
```
