### ISSUE TITLE
I cannot install colorls successfully on Windows 10

### ISSUE THREAD

**Issue by sql-sith** [athityakumar/colorls#424]
### Description

I am a developer, but I am not a ruby person, so the solutions to my problems may be simple to other folks (I hope so!).

I have tried to install `colorls `on `Windows 10 2004, Build 20262.1010` (not WSL) with `pwsh 7.1.0`. I went directly to the Ruby site and download the Windows installer for Ruby 2.7.2-1 (x64). Then I installed `colorls `using `scoop`. Next, I fired up a new `pwsh `and ran `gem install colorls`. This failed immediately with these messages:

```
chris@cahokia > gem install colorls
Traceback (most recent call last):
        15: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
        14: from <internal:gem_prelude>:1:in `require'
        13: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems.rb:1424:in `<top (required)>'
        12: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems.rb:1424:in `require'
        11: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/defaults/operating_system.rb:3:in `<top (required)>'
        10: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/singleton.rb:27:in `enable_dll_search_paths'
         9: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:99:in `enable_dll_search_paths'
         8: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:89:in `mingw_bin_path'
         7: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:76:in `msys_path'
         6: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:48:in `iterate_msys_paths'
         5: from C:/Ruby27-x64/lib/ruby/2.7.0/win32/registry.rb:542:in `open'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/win32/registry.rb:435:in `open'
         3: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:49:in `block in iterate_msys_paths'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/win32/registry.rb:611:in `each_key'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/win32/registry.rb:910:in `export_string'
C:/Ruby27-x64/lib/ruby/2.7.0/win32/registry.rb:910:in `encode': U+00AE to IBM437 in conversion from UTF-16LE to UTF-8 to IBM437 (Encoding::UndefinedConversionError)
```
I also get the same errors shown above when I try to run `ruby` by itself. `rubyw` actually popped up a window, but that window terminated very quickly and posted no information back my terminal

I am not a `rubyenv` user, so the advice to run `rubyenv rehash` and `rehash` did not help in my case.

At this point I decided that I wasn't making progress, so I uninstalled everything. Any advice? Thanks much.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [x] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature???
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Hi.

Have a look here - https://bugs.ruby-lang.org/issues/10300 and here https://stackoverflow.com/questions/53891910/gem-install-jekyll-failure

HTH

**Comment by avdv** [comment]
BTW, U+00AE is the character ® which you seem to have used somewhere in your msys paths. Look into the registry under `HKEY_CURRENT_USER/SOFTWARE/Microsoft/Windows/CurrentVersion/Uninstall/`.

It should help starting ruby with `-E utf-8`, ie. `export RUBYOPT="-E utf-8"` before running `gem`.
