### ISSUE TITLE
error while running colorls "missing compatible arch"

### ISSUE THREAD

**Issue by im-AMS** [athityakumar/colorls#425]
**OS: macos bigsur, apple m1**

when i try to run colorls I get this
```
Traceback (most recent call last):
	10: from /usr/local/bin/colorls:23:in `<main>'
	 9: from /usr/local/bin/colorls:23:in `load'
	 8: from /Users/ams/.gem/ruby/2.6.0/gems/colorls-1.4.3/exe/colorls:21:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/ams/.gem/ruby/2.6.0/gems/colorls-1.4.3/lib/colorls.rb:9:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Library/Ruby/Gems/2.6.0/gems/clocale-0.0.4/lib/clocale.rb:15:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/clocale-0.0.4/lib/clocale/clocale.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/clocale-0.0.4/lib/clocale/clocale.bundle - /Library/Ruby/Gems/2.6.0/gems/clocale-0.0.4/lib/clocale/clocale.bundle (LoadError)
```
- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Bug in existing feature

**Comment by avdv** [comment]
Seems like Ruby is still not really well supported on arm64 darwin. You could work around with `arch -x86_64 /bin/bash` and install the x86 version of ruby and colorls gem.

https://www.driftingruby.com/episodes/a-rubyist-s-apple-m1-review
> HOWEVER, I just cannot recommend this approach at this moment until things get ironed out. There are still too many issues and compatibility problems with the Ruby ARM Version. I've found a few crashes and it's just not stable enough. For now, continue to use the Ruby x86 version.

**Comment by dbhagen** [comment]
For me, I modified my ~/.zshrc where I had:
```bash
if type "colorls" >/dev/null 2>/dev/null; then
source $(dirname $(gem which colorls))/tab_complete.sh
alias ls='colorls'
fi
```
to be:
```bash
if type "colorls" >/dev/null 2>/dev/null; then
source $(dirname $(gem which colorls))/tab_complete.sh
alias ls='arch -x86_64 colorls'
fi
```

This could also be `alias colorls='arch -x86_64 colorls'` if that fits your workflow better.
