### ISSUE TITLE
NilClass Exception on an empty directory

### ISSUE THREAD

**Issue by mjurczyk** [athityakumar/colorls#71]
On MacOS when trying to `colorls / colorls -r` an empty directory, following errors get thrown:

```
/Users/-/.rvm/gems/ruby-2.3.0/gems/colorls-0.1.4/lib/colorls/core.rb:103:in `in_line': undefined method `+' for nil:NilClass (NoMethodError)
	from /Users/-/.rvm/gems/ruby-2.3.0/gems/colorls-0.1.4/lib/colorls/core.rb:87:in `chunkify'
	from /Users/-/.rvm/gems/ruby-2.3.0/gems/colorls-0.1.4/lib/colorls/core.rb:20:in `ls'
	from /Users/-/.rvm/gems/ruby-2.3.0/gems/colorls-0.1.4/lib/colorls/flags.rb:19:in `process'
	from /Users/-/.rvm/gems/ruby-2.3.0/gems/colorls-0.1.4/exe/colorls:4:in `<top (required)>'
	from /Users/-/.rvm/gems/ruby-2.3.0/bin/colorls:23:in `load'
	from /Users/-/.rvm/gems/ruby-2.3.0/bin/colorls:23:in `<main>'
	from /Users/-/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/-/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Not really a no-go issue, but quite ugly.

**Comment by athityakumar** [comment]
@mjurczyk - I think this has already been fixed and released with v0.1.5. Try `gem update colorls`. 😄
