### ISSUE TITLE
Trouble with dependency?

### ISSUE THREAD

**Issue by schvabodka-man** [athityakumar/colorls#94]
Hi there. I've installed app and when i'm running it i get

/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:127:in `require': /usr/local/lib64/gems/ruby/ruby-terminfo-0.1.1/terminfo.so: undefined symbol: setupterm - /usr/local/lib64/gems/ruby/ruby-terminfo-0.1.1/terminfo.so (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/share/gems/gems/ruby-terminfo-0.1.1/lib/terminfo.rb:31:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/colorls-0.1.7/lib/colorls.rb:4:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/share/gems/gems/colorls-0.1.7/exe/colorls:3:in `<top (required)>'
	from /usr/local/bin/colorls:22:in `load'
	from /usr/local/bin/colorls:22:in `<main>'

I don't have rubyenv installed, i've nerd-fonts installed in my terminal

**Comment by athityakumar** [comment]
Hey @schvabodka-man, thanks for filing this issue. Can you please try `sudo apt-get install libncurses5-dev` followed by `gem install colorls`?

**Comment by schvabodka-man** [comment]
I've ncurses installed but must this be ncurses 5? I've ncurses 6 installed with devel libs and there is no ncurses 5 -devel in fedora repo. But i've installed ruby-ncurses(wondering if maybe it will help) but i'm still getting this error

**Comment by mscottnelson** [comment]
Just performed a 'brew update' and running into a similar kind of problem:
/usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/usr/local/lib/ruby/gems/2.4.0/gems/ruby-terminfo-0.1.1/lib/terminfo.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.1.dylib (LoadError)
  Referenced from: /usr/local/lib/ruby/gems/2.4.0/gems/ruby-terminfo-0.1.1/lib/terminfo.bundle
  Reason: image not found - /usr/local/lib/ruby/gems/2.4.0/gems/ruby-terminfo-0.1.1/lib/terminfo.bundle
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/ruby-terminfo-0.1.1/lib/terminfo.rb:31:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/colorls-0.1.7/lib/colorls.rb:4:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/colorls-0.1.7/exe/colorls:3:in `<top (required)>'
	from /usr/local/bin/colorls:23:in `load'
	from /usr/local/bin/colorls:23:in `<main>'

**Comment by mscottnelson** [comment]
Although the case may be different than your's, @schvabodka-man, deleting /usr/local/lib/ruby/gems/2.4.0 and reinstalling colorls fixed this error for me.

**Comment by soulomoon** [comment]
I have the sam problem and
turns out uninstall ruby-terminfo
```
gem uninstall ruby-terminfo
gem install ruby-terminfo
```
help me with it

**Comment by athityakumar** [comment]
@soulomoon - Can you please screenshot / paste the error here?

**Comment by soulomoon** [comment]
@athityakumar I am afraid I can not, because after the reinstallation of the ruby-terminfo, my error is gone. 
It was fine in the first installation, but after I have done a brew update and gem update, it went bad.

**Comment by athityakumar** [comment]
For everyone who've faced this issue, the terminfo dependency has been removed, and replaced in v1.0.6. Please try `gem install colorls` (or, `gem update colorls`) again, in case you weren't able to successfully install earlier. If the issue seems fixed, we can close this issue. 😄

**Comment by schvabodka-man** [comment]
Ok, it's installable and works pretty neat. You can close this issue
